#!/bin/bash

LAYER_NAME='A VALID LAMBDA LAYER NAME + ZIP EXTENSION.zip'
DESCRIPTION="A SIMPLE DESCRIPTION"

# A LIST OF PACKAGE TO INSTALL, SPACE SEPARATED
PACKAGES="A LIST OF PACKAGE TO INSTALL, SPACE SEPARATED"

RUNTIMES="python3.7 OR OTHER RUNTIMES. Contains: $PACKAGES"
