AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  model-one

Globals:
  Function:
    Timeout: 3

Resources:
  ModelOneFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: model_one/
      Handler: app.lambda_handler
      Runtime: python3.7
      Layers:
        - arn:aws:lambda:eu-west-1:667992618030:layer:python37_numpy1182:2
        - arn:aws:lambda:eu-west-1:667992618030:layer:python37_scipy141:1
        - arn:aws:lambda:eu-west-1:667992618030:layer:python37_scikitlearn0221_joblib0141:1
